title: My Personal Website
description: A personal website with a blog.

collections:
  posts:
    output: true
    permalink: /blog/:title/
  youtubes:
    output: true
    permalink: /youtube/:title/
  instagrams:
    output: true
    permalink: /instagram/:title/
